name: Tests

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  tests:
    runs-on: ubuntu-22.04

    services:
      mariadb:
        image: mariadb:lts
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      meilisearch:
        image: getmeili/meilisearch:latest
        ports:
          - 7700:7700
        options: --health-cmd="wget --no-verbose --spider http://localhost:7700/health" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: cp .env.ci .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis-phpredis/phpredis@5.3.7, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none
        env:
          REDIS_CONFIGURE_OPTS: --enable-redis --enable-redis-igbinary --enable-redis-msgpack --enable-redis-lzf --with-liblzf --enable-redis-zstd --with-libzstd --enable-redis-lz4 --with-liblz4
          REDIS_LIBS: liblz4-dev, liblzf-dev, libzstd-dev

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Set Minimum PHP 8.2 Versions
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require guzzlehttp/psr7:^2.4 --no-interaction --no-update

      - name: Install Composer dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Install NPM dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: npm ci

      - name: Generate app key
        run: php artisan key:generate

      - name: Run table migrations
        run: php artisan migrate --force
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          DB_USERNAME: root

      - name: Build assets
        run: npm run build --if-present

      - name: Execute tests
        run: vendor/bin/pest --parallel
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          DB_USERNAME: root
          PATH_TOKEN: ${{ secrets.PATH_TOKEN }}

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
